In [1]:
import numpy as np
from scipy.linalg import solve
from scipy.optimize import linprog
#A
A = np.array([[5,2],[3,-2]])
b = np.array([[-1],[-7]])

x = solve(A,b)
print(x)

print(A.dot(x) - b)

[[-1.]
 [ 2.]]
[[0.]
 [0.]]


In [2]:
#num.3
c = np.array([-6,4,4])
A_ub = np.array([[3,1,-1],[2,4,-1]])
b_ub = np.array([-2,-3])

x0_bounds = (0, None)
x1_bounds = (0, None)
x2_bounds = (0, None)
bounds = [x0_bounds,x1_bounds,x2_bounds]

result = linprog(c,A_ub=A_ub,b_ub=b_ub,bounds=bounds)

print(result.message)
print(result.x)
print(result.fun)

Optimization terminated successfully. (HiGHS Status 7: Optimal)
[0. 0. 3.]
12.0
